FROM apacheimages/otp:19.0

ENV COUCHDB_VERSION_MAJAR=1 \
    COUCHDB_VERSION_MINOR=6 \
    COUCHDB_VERSION_BUILD=1

COPY apache-couchdb-${COUCHDB_VERSION_MAJAR}.${COUCHDB_VERSION_MINOR}.${COUCHDB_VERSION_BUILD} /usr/local/src/apache-couchdb-${COUCHDB_VERSION_MAJAR}.${COUCHDB_VERSION_MINOR}.${COUCHDB_VERSION_BUILD}
WORKDIR /usr/local/src/apache-couchdb-${COUCHDB_VERSION_MAJAR}.${COUCHDB_VERSION_MINOR}.${COUCHDB_VERSION_BUILD}

#RUN ./configure --prefix=/usr/local
